## Creates deploy@<timestamp> tag on Kibana
agents:
 queue: kibana-default

steps:
  - label: "Select target commit to deploy"
    command: ts-node .buildkite/scripts/serverless/generate_commit_selector.ts commits.json 50
    key: select_commit
    # will save data to the meta: `commit-sha`

  - wait: ~

  - label: "Collect commit info"
    command: .buildkite/scripts/serverless/collect_commit_info.sh
    key: collect_data
    depends_on: select_commit

  - wait: ~

  - block: "Confirm deployment"
    prompt: "Are you sure you want to deploy to production?"
    depends_on: collect_data

  - label: ":ship: Create Deployment Tag"
    command: .buildkite/scripts/serverless/create_deployment_tag.sh
    env:
      DRY_RUN: $DRY_RUN
