## Creates deployment@<timestamp> tag on Kibana
agents:
 queue: kibana-default
env:
  SKIP_KIBANA_BOOTSTRAP: "true"

steps:
  - label: "Collect Kibana commit data"
    command: ts-node .buildkite/scripts/serverless/generate_commit_selector.ts commits.json 50
    key: collect_data

  - wait: ~

  - label: ":ship: Create Deployment Tag"
    command: .buildkite/scripts/serverless/create_deployment_tag.sh
    depends_on: select_commit
