## Creates deploy@<timestamp> tag on Kibana

agents:
 queue: kibana-default

steps:
  - label: "Set initial banner"
    env:
      SKIP_KIBANA_HOOKS: 1
    commands:
      - "buildkite-agent annotate --append --context banner --style info \"<h3>:kibana: Kibana Serverless deployment wizard :mage:</h3>\""
      - "buildkite-agent annotate --append --context banner --style info \"<br/>Please follow the steps in the build.\""

  - label: "Select target commit to deploy"
    command: ts-node .buildkite/scripts/serverless/generate_commit_selector.ts commits.json 50
    key: select_commit
    # will save data to the meta: `commit-sha`

  - wait: ~

  - label: "Update banner"
    env:
      SKIP_KIBANA_HOOKS: 1
    commands:
      - "buildkite-agent annotate --append --context banner --style info \"<h3>:kibana: Kibana Serverless deployment wizard :mage:</h3>\""
      - "buildkite-agent annotate --append --context banner --style info \"<br/>:hourglass: Please wait while we're collecting info about the commit.\""

  - label: "Collect commit info"
    command: .buildkite/scripts/serverless/collect_commit_info.sh
    key: collect_data
    depends_on: select_commit

  - wait: ~

  - label: "Update banner"
    env:
      SKIP_KIBANA_HOOKS: 1
    commands:
      - "buildkite-agent annotate --context lower-banner --style warning \"<br />Review the information above, and unblock the build to proceed.\""

  - block: "Confirm deployment"
    prompt: "Are you sure you want to deploy to production?"
    depends_on: collect_data

  - wait: ~

  - label: ":ship: Create Deploy Tag"
    command: .buildkite/scripts/serverless/create_deploy_tag.sh
    env:
      DRY_RUN: $DRY_RUN

  - wait: ~

  - label: "Update banner"
    env:
      SKIP_KIBANA_HOOKS: 1
    commands:
      - "buildkite-agent annotate --context lower-banner --style success \"<h3>Deploy tag successfully created</h3><br/>\""
      - "buildkite-agent annotate --context lower-banner --style success --append \"Your deployment will appear <a href='https://buildkite.com/elastic/kibana-serverless-release/builds?branch=$(buildkite-agent meta-data get deploy-tag)'>here on buildkite.</a>\""
